apiVersion: apps/v1
kind: Deployment
metadata:
  name: luxemarket-api-deployment
  labels:
    app: luxemarket-api
spec:
  replicas: 6 # Runs 4 copies of your app across your worker nodes
  selector:
    matchLabels:
      app: luxemarket-api
  template:
    metadata:
      labels:
        app: luxemarket-api
    spec:
      containers:
      - name: luxemarket-api
        image: umerali2727/luxemarket-api:latest # Your Docker Hub Image
        imagePullPolicy: Always
        ports:
        - containerPort: 3001 # The port your Express app exposes
        env:                     # <-- Add this environment variables block
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "umerali27"
        - name: DB_PASSWORD
          value: "ummeloiza@10"
        - name: DB_NAME
          value: "luxemarket"
