apiVersion: apps/v1
kind: Deployment
metadata:
  name: luxemarket-api-deployment
  labels:
    app: luxemarket-api
spec:
  replicas: 4 # Runs 4 copies of your app across your worker nodes
  selector:
    matchLabels:
      app: luxemarket-api
  template:
    metadata:
      labels:
        app: luxemarket-api
    spec:
      containers:
      - name: luxemarket-api
        image: umerali2727/luxemarket-api:latest# Your Docker Hub Image
        imagePullPolicy: Always
        ports:
        - containerPort: 3001 # The port your Express app exposes

